### ISSUE TITLE
Check Microarray dataset is a good with Jake.

### ISSUE THREAD

**Issue by JSchoenbachler** [hugheylab/seeker#13]
@jakejh could you check the array local function and make sure it's cool with you? Here are the lines for the test-

https://github.com/hugheylab/seeker/blob/0463f108904107c1c5460076a392b5de45683428/tests/testthat/test-array.R#L63-L78

And the folder is `./tests/testthat/data/LOCAL01/`.

**Comment by jakejh** [comment]
1. No files other than cel.gz need to be in the raw folder.
2. I'd like to use smaller cel.gz file than what you have now. Even the ones from GSE54650 are only 4.3 MB or so, and hopefully we can do better than that.

**Comment by jakejh** [comment]
And please shorten the variable names for readability.

**Comment by JSchoenbachler** [comment]
@jakejh here is the new dataset I'm using- https://www.ncbi.nlm.nih.gov/geo/query/acc.cgi?acc=GSM5111233
It's only 3.5 MB and the tar.gz is now 13.9 MB.

I will shorten the variable names.

**Comment by JSchoenbachler** [comment]
Both are resolved in this commit- 1b906721f509cc756b262e9f2b26eb155376a645
