### ISSUE TITLE
need to also save version of SRA Toolkit

### ISSUE THREAD

**Issue by jakejh** [hugheylab/seeker#31]
namely, `prefetch` and `fasterq-dump`, as these aren't part of the conda environment.

https://github.com/hugheylab/seeker/blob/29273fdc8040fa3ef56c385cf5a3592277d7709c/R/seeker.R#L510

**Comment by JSchoenbachler** [comment]
See commit here: https://github.com/hugheylab/seeker/commit/9df3a16e668e834cbeaed110eb6c514545c06011

Rolling into the `cran-prep` branch.
