### ISSUE TITLE
Missing `file.path` in many places

### ISSUE THREAD

**Issue by jakejh** [hugheylab/seeker#6]
This is what I meant with not being lazy about `file.path`.

https://github.com/hugheylab/seeker/blob/fa2ce19147cbd34c020560d4d89cc825a73672b1/tests/testthat/test-fetch.R#L18

**Comment by JSchoenbachler** [comment]
@jakejh I had fixed all of these (I'm pretty sure) last week, and when you posted this it had already been fixed (link points to an old commit version). I'll leave this open in case there are any more I miss, but it should be fine!
