### ISSUE TITLE
checkmate::assert inconsistent output

### ISSUE THREAD

**Issue by JSchoenbachler** [hugheylab/seeker#9]
@jakejh This is a weird issue. It started when these lines (which are now updated):
https://github.com/hugheylab/seeker/blob/d34ad31e641fef9ec009ed766efeee3cc7daa6b7/tests/testthat/test-seeker.R#L103-L105
failed when actually testing the package, but passed when I ran line by line myself.

The problem (I think) is that `checkmate::assert()` modifies the error output **based on the window size of your terminal**. Apart from this being really dumb anyways, consider the following output of the function (the one that was failing for me):
```
Error: Assertion failed. One of the following must apply:
 * checkNames(names(params$tximport$tx2gene)): Must include the elements {species}
 * checkNames(names(params$tximport$tx2gene)): Must be a identical to (filename) 
```
Based on that, the original regex statement to catch this error was:
```
regexp = paste0('.*checkNames\\(names\\(params\\$tximport\\$tx2gene\\)\\).*Must include the elements(\\n|.)*',
                             'checkNames\\(names\\(params\\$tximport\\$tx2gene\\)\\).*Must be a identical to(\\n|.)*')
```
Which succeeded when running line by line in my standard terminal window. However, when actually running as tests and the output was in the test pane of RStudio, the output changed to this:
```
Error: Assertion failed. One of the following must apply:
 * checkNames(names(params$tximport$tx2gene)): Must include the 
 * elements {species}
 * checkNames(names(params$tximport$tx2gene)): Must be a identical to 
 * (filename) 
```
So my regex wouldn't match.

All of that to say, my current regex will catch the output even if it is truncated like in the last example, but do we want it to be this way? Also, is this something worth bringing up to the checkmate repo as an issue that can be hard to test for? Would like to know what you think.

**Comment by JSchoenbachler** [comment]
Per Jake feedback, only check assertions (ex.- `checkNames(names(params$tximports$tx2gene))`)

Follow up once done, but also can just check for error instead of matching error.

**Comment by JSchoenbachler** [comment]
@jakejh the regex is updated! Let me know if you'd prefer it the way I have it or if you'd prefer just setting `regexp = NULL` and not validating the error message at all!

**Comment by jakejh** [comment]
I appreciate the hard work on the regex, but I don't love depending on it in the tests. I think it's not very readable and is too brittle, depending too much on our implementation of the logic and on checkmate. For now I prefer just checking that the code does or doesn't return an error.

**Comment by JSchoenbachler** [comment]
Okay, removed the regex on the newer branch.
